// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytegircevnaewgqpbked.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZWdpcmNldm5hZXdncXBia2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTU1MzcsImV4cCI6MjA2NTEzMTUzN30.ectpPhTNG-IGEl4uzSTI-rWeTMfK5hdcdhu4SxteORY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);